### ISSUE TITLE
Load bib file when only markdown files are open

### ISSUE THREAD

**Issue by smartens** [notZaki/PandocCiter#10]
**Problem**
I use the latex markdown package. So to inject my markdown files I use `/markdownInput`. The Problem is that the bib file doesn't get loaded when only markdown files are open. I have to open a tex file so that the bib file gets loaded.

My configuration is
```
  "PandocCiter.DefaultBib": "sources.bib",
  "PandocCiter.ForgetUnusedBib": false,
  "PandocCiter.ShowLog": true,
  "PandocCiter.UseDefaultBib": true,
  "PandocCiter.ViewType": "browser",
```

**Expected behavior**
The bib file gets loaded when there is a markdown file open, so I don't need to open a tex file to cite in markdown.

**Log files**
```
PandocCiter is now activated
Looking for .bib file: sources.bib
Looking for .bib file: sources.bib
Showing 0 suggestions
Showing 0 suggestions
Looking for .bib file: sources.bib
Showing 0 suggestions
Looking for .bib file: sources.bib
Looking for .bib file: sources.bib
Looking for .bib file: sources.bib
Looking for .bib file: sources.bib
Looking for .bib file: sources.bib
# Here I opened my thesis.tex
Found .bib file /workspaces/markdown-thesis/sources.bib
Creating file watcher for .bib files.
Parsing .bib entries from /workspaces/markdown-thesis/sources.bib
Parsed 28 .bib entries from /workspaces/markdown-thesis/sources.bib.
Looking for .bib file: sources.bib
Found .bib file /workspaces/markdown-thesis/sources.bib
Adding .bib file /workspaces/markdown-thesis/sources.bib to bib file watcher.
Parsing .bib entries from /workspaces/markdown-thesis/sources.bib
Parsed 28 .bib entries from /workspaces/markdown-thesis/sources.bib.
```

**Comment by notZaki** [comment]
Thanks for the detailed description.

I think the `DefaultBib` configuration needs to be an absolute path instead of a relative one, so the configuration should be:
```
"PandocCiter.DefaultBib": "full/path/to/sources.bib",
```

It is surprising that the bib file was loaded by opening the thesis.tex file. Were the three files (markdown, tex and bib) in the same folder?

**Comment by smartens** [comment]
Indeed `"PandocCiter.DefaultBib": "/workspaces/markdown-thesis/sources.bib"` did the trick.
