### ISSUE TITLE
Provide autocompletion for custom BibEntries

### ISSUE THREAD

**Issue by smartens** [notZaki/PandocCiter#12]
**Problem**
I have to use a custom BibEntry for Standards but I can't select this custom BibEntry in autocompletion.
I noticed that the BibTex Entries are hardcoded in https://github.com/notZaki/PandocCiter/blob/master/src/providers/completer/citation.ts. The version of latex workshop https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completer/citation.ts does read all the entries from the actual bibtex.

**Expected behavior**
I want to autocomplete custom BibEntries.

**Comment by notZaki** [comment]
It looks like LaTex-Workshop uses the [latex-utensils](https://www.npmjs.com/package/latex-utensils) package to parse the bib files.

I adapted their code into the current master. Before publishing it, I would appreciate it if you could try it out and check if it solves the issue. 

The extension can be built by cloning this repository, installing the dependencies using `npm install` and then running it through vscode's debugger.
Alternatively, [this zip files contains a pre-build vsix file.](https://github.com/notZaki/PandocCiter/files/4333389/pandocciter-0.4.3.vsix.zip)

**Comment by smartens** [comment]
It works :) ... I used the pre-built file. 
Thanks 👍

**Comment by notZaki** [comment]
Thanks for testing it out. I re-labeled and published this version as 0.5.0.
