### ISSUE TITLE
Search whole folder for default bib file

### ISSUE THREAD

**Issue by smartens** [notZaki/PandocCiter#13]
Hi, me again.

I just noticed that PandocCiter only searches for the DefaultBib in the folder of the opened editor. 

My defaultbib is in the root folder. My markdown files are in the folder and subfolders of the folder document. Right now PandocCiter is only searching for the bib file in the folder of the opened file e.g. /document/chapter01/...

I think when the bib file is relative specified than it would make sense to search the whole folder.
Something like this should do it:
`vscode.workspace.findFiles(configuration.get('DefaultBib')).then(x => {bibFile = x[0]}); `

Maybe this is also useful if multiple defaultbibs are specified.

**Comment by notZaki** [comment]
I like the suggestion, however, I would prefer if the behavior was explicit. 

How about if, instead of searching for the bib file, we allowed placeholders in the DefaultBib configuration? For example, add a feature where the following configuration
```
"PandocCiter.DefaultBib": "{WORKSPACE}/bibFolder/sources.bib",
```
would resolve `{WORKSPACE}` to the absolute path of the workspace folder.

**Comment by smartens** [comment]
This is also a good solution. Let me know if I should test something.

**Comment by notZaki** [comment]
I published version 0.6.0 which should support `${workspaceFolder}` in the DefaultBib path. An example configuration would look like:
```
"PandocCiter.DefaultBib": "${workspaceFolder}/bibFolder/sources.bib"
```

The naming convention is similar to [vscode's pre-defined variables](https://code.visualstudio.com/docs/editor/variables-reference).

I did a quick test on a windows machine and it seemed to work. Let me know if any problems arise.
Thanks.

**Comment by notZaki** [comment]
I changed my mind. 

I think it would be more intuitive if relative paths in DefaultBib were always resolved using the workspace folder. I can't think of a situation where the current behaviour would be practical, i.e. having DefaultBibs which are relative to the opened file.

The updated version (0.7.0) will assume that relative DefaultBib paths are relative to the workspace folder, i.e. the configuration should look like
```
"PandocCiter.DefaultBib": "./bibFolder/sources.bib"
```
where the `./` is optional.

**Comment by smartens** [comment]
Agreed ... more intuitive and simple. Version 0.7.0 works great 😄👍.
