### ISSUE TITLE
Allow extension to run for pandoc-alike markdown languages

### ISSUE THREAD

**Issue by gadenbuie** [notZaki/PandocCiter#2]
First, thank you for this extension -- it's excellent!

I'm wondering if it would be possible for this extension to work on other pandoc-like language types. My particular use case is R Markdown, which I believe has a language id `rmd` provided by the [vscode-R extension](https://github.com/Ikuyadeu/vscode-R). Admittedly, I'm probably an edge case, so if there are local modifications I can make to get this to work, I'd appreciate any tips. The extension works fine if I temporarily change the language to "markdown" but I lose other features and toggling back and forth isn't the greatest.

**Comment by notZaki** [comment]
I use R Markdown too (or rather, Bookdown), but not the `rmd` language so I hadn't considered it.

The latest release (0.1.0) should support the `rmd` language.
It should also highlight the references. Based on [this issue](https://github.com/Ikuyadeu/vscode-R/issues/36), I'm assuming the Rmd language doesn't have its own highlighting for references, but if it does then that might lead to conflicts. Let me know if there are any conflicts, in which case I'll disable the highlighting for `rmd` documents.

**Comment by gadenbuie** [comment]
It works for me, including reference highlighting, thank you for such a quick turnaround!
