### ISSUE TITLE
Integrate with pandoc-crossref

### ISSUE THREAD

**Issue by d0rf3n** [notZaki/PandocCiter#20]
Any way that an option to use this together with [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) could be added?

It can refer to different identifiers, uses for example the #sec, #fig, #tbl id to refer to headings, figures and tables respectively.

**Comment by notZaki** [comment]
The latest release (0.9.1) should now support auto-completion for pandoc-crossref, thanks to @yarray
