### ISSUE TITLE
Two inline preview issues

### ISSUE THREAD

**Issue by tstenner** [notZaki/PandocCiter#21]
First of all, thanks for this great extension!

There's two minor things I've noticed in the display for the following bib file:

```
@article{Wrong,
annote = {This is a haiku
It has multiple newlines
That are not displayed},
author = {Author},
title = {{Wrongly displayed entry}}
}

@article{Correct,
author = {Author},
title = {{Correctly displayed entry}},
annote = {This is a haiku
It has a double newline.

It shows correctly}
}

```

Firstly, the order of the display follows the order of the attributes in the entry, not the one configured in `PandocCiter.CitationFormat` (i.e. `annote` should be displayed as last line). Secondly, the entry is formatted as a single line (even fields that contain newlines), unless one of the displayed entry has an empty line:

![pandocciter_correct](https://user-images.githubusercontent.com/920936/115023137-a8ecd400-9ebe-11eb-83cd-0fb2bdcd85b5.png)
![pandocciter_wrong](https://user-images.githubusercontent.com/920936/115023141-a9856a80-9ebe-11eb-8894-69c748291256.png)

**Comment by notZaki** [comment]
Thanks for pointing this out.

I tried fixing this in the latest release (0.9.0). Could you check if the issue is still present?

**Comment by tstenner** [comment]
Looks great in both cases, thanks for the quick fix!
