### ISSUE TITLE
No dropdown menu, no output log produced

### ISSUE THREAD

**Issue by lmuenter** [notZaki/PandocCiter#22]
Hi,

after installing Pandoc Citer, the extension seemingly doesn't parse my .bib-file, and no dropdown menu is produced when using [@] or [ctrl + space]. When checking for a log under the "Output"-tab, the log remains empty. 

I'm running VSCode on Windows 10. After installing the extension, entries for Pandoc Citer are found in the settings.json. The extension vscode-pandoc is installed, and pandoc is also available via the command line. 

Am I doing something wrong?

Here are the entries in the settings.json:

``` json

	// List of fields displayed in preview
	"PandocCiter.CitationFormat": [
		"author",
		"title",
		"journal",
		"publisher",
		"booktitle",
		"year"
	],

	// Path to default bib file
	"PandocCiter.DefaultBib": "",

	// Whether to forget bib file when changing documents
	"PandocCiter.ForgetUnusedBib": true,

	// Main document containing YAML for bibliography
	"PandocCiter.RootFile": "",

	// Should log be shown in Output panel
	"PandocCiter.ShowLog": false,

	// Whether to use the Default Bib
	"PandocCiter.UseDefaultBib": true,

	// How citation completions are shown
	"PandocCiter.ViewType": "inline",

```

**Comment by notZaki** [comment]
Try setting:
```
"PandocCiter.ShowLog": true,
```
and then restarting vscode. The log should then show up in the "Output" tab.

Does the markdown file have a YAML header containing a `Bibliography: [path/to/file.bib]` entry? If not, then that can either be added, or add it to the setting:
```
"PandocCiter.DefaultBib": "path/to/file.bib"
```

**Comment by lmuenter** [comment]
Hello,

adding the setting

```
"PandocCiter.DefaultBib": "path/to/file.bib"
```

seems to have worked. However, the extension still does not output any messages. Anyways, I can now prepare documents for rendering with pandoc and pandoc-citeproc, so I'm happy! I think I'll close this issue.

Thank you!
