### ISSUE TITLE
More yaml bibbliography entry

### ISSUE THREAD

**Issue by crystalfp** [notZaki/PandocCiter#23]
Thanks for this very useful extension!

Currently, in the YAML header, I have:
```
bibliography: ["file1.bib","file2.bib"]
```
And this works without problems, also with `pandoc`.
But if I try to format the entry in a more YAML-ly way, which is:
```
bibliography:
  - file1.bib
  - file2.bib
```
this gets ignored by the extension, even if the two formats describe the same array.
Am I missing something? Or is it a feature that I could ask to be implemented?
Thanks!
mario

**Comment by notZaki** [comment]
Unfortunately, the extension currently has a very simple way of identifying the bib files, which is why they have to be written in the first format.
The 2nd format could be supported by using a yaml parser, though I likely won't have time to try this until the end of the year.

**Comment by notZaki** [comment]
Well, it turns out that I'm not good at estimating time.

Anyways, the YAML-ly format should now work with the latest release (`0.10.0`)

**Comment by crystalfp** [comment]
No way... I have disabled all extensions except Pandoc Citer and ctrl-space came up with a generic autocomplete.
Enabling log gives:
```
PandocCiter is now activated
Reacting to document open
```
Trying to reinstall the extension

**Comment by notZaki** [comment]
That doesn't sound good. Sometimes, the extension doesn't work when it is first installed, but closing/re-opening vscode tends to fix it. 🤷

**Comment by crystalfp** [comment]
De-installed, Reinstalled, disabled all extensions except Citer, using the old or the new format... No way. The autocomplete does not trigger and ctrl-space gives a generic autocomplete.
Desperate.

**Comment by notZaki** [comment]
That's unfortunate. The old version worked but the new one doesn't?

I just made a sample repository [here](https://github.com/notZaki/PandocCiterSample) and ran it with codespaces and installed the extension there, and it seems to work. You're not the first person to have suggestions not show up, so there likely are some gremlins, but I can never seem to replicate it on my end. 😕

**Comment by crystalfp** [comment]
OK, with version 0.9.3 and the old bibliography format it works even if you need to push ctrl-space after entering `@`
With 1.0.0 it does not work.
The same with your repository:
![image](https://github.com/notZaki/PandocCiter/assets/865866/3de9a250-779c-4d3f-96b3-8598c5409bfd)
Disabling Tabnine extension:
![image](https://github.com/notZaki/PandocCiter/assets/865866/ff76c15b-e951-483e-a859-469fe7fb74de)
Is there any debug mode so I can collect more info for you?
Thanks!
mario

**Comment by crystalfp** [comment]
The new version (0.10.2) has solved the problem!
Thanks!

**Comment by crystalfp** [comment]
Accc... spoke too fast. It works with the old format and on both on your example, on mine it works only with the old format. With the new:
![image](https://github.com/notZaki/PandocCiter/assets/865866/ca0893d5-d69a-4527-9fe6-647bc92b8e0c)
With the old
![image](https://github.com/notZaki/PandocCiter/assets/865866/0d49cabe-e9a2-4d10-97b1-22dbff65030f)

**Comment by crystalfp** [comment]
The problem are the spaces in the first bib filename. When I put quotes around "Computational thinking Bibliography.bib" it works with the new format!
Thanks again!
mario
