### ISSUE TITLE
Read citation information from CSL JSON

### ISSUE THREAD

**Issue by adunning** [notZaki/PandocCiter#34]
Thank you for this absolutely brilliant extension. The native format for `pandoc-citeproc` is CSL JSON, and it would be wonderful if you could support the ability to read these files as well as BibTeX. I expect that many Pandoc users will be using your extension with Zotero and its Better BibTeX for Zotero extension, which can export directly to CSL JSON or CSL YAML to avoid the encoding issues that can come with BibTeX.

**Comment by davvalent** [comment]
That's my case! I support @adunning's suggestion!

**Comment by notZaki** [comment]
Thanks for the suggestion! 

I don't use CSL JSON, but I added some initial support in the latest release (`0.10.0`). Now a json file can be included in the yaml header and everything else should work. 🤞 

Let me know if it doesn't work—although I'd rather be told that it does work. 🙃

**Comment by adunning** [comment]
This works perfectly: very many thanks indeed!
