### ISSUE TITLE
Rather than requiring a root file, allow specifiying default bibtex file

### ISSUE THREAD

**Issue by sbaack** [notZaki/PandocCiter#4]
While I'm at it, there is one more thing I would like to suggest :-) I usually do not create bibtex files on a project basis; most of the time I just use one bibtex file with my entire library.

PandocCiter allows me to do that, but I need to create a 'root file' that contains a YAML header pointing to the actual bibtex file. Rather than requiring an extra root file, I think it would be much easier if we could just directly point to a default bibtex file in the settings, something like `"PandocCiter.DefaultLibrary": "~/Documents/library.bib"`. If the file I'm currently working on contains a YAML header pointing to a different bibtex file, then PandocCiter should prefer it over the default (or it should use both the default and project library, perhaps configurable by the user). I think this would be easier to set up and more intuitive.

**Comment by notZaki** [comment]
The 0.3.0 version of the package has a `PandocCiter.DefaultBib` configuration/setting. 
It will require an absolute path to a single bib file, so `~` will have to be replaced with `/home/username` or however it is defined. 

If the working file has a YAML header pointing to a different bib file, then both files will be loaded.
To disable this behaviour, there is another setting `PandocCiter.UseDefaultBib` which might be useful as a workspace-specific configuration.

I only did a quick test to see if it works, so let me know if there are any issues.

**Comment by sbaack** [comment]
Wow, you're awesome! Just did a quick test as well and it is working fine. Will let you know if I encounter issues. But I think you can close this again...in record time :-)
