### ISSUE TITLE
cannot find relative bibliography file when md file is not in the root workspace directory

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [notZaki/PandocCiter#47]
Hi, first, a great extension. Thank you.

I encountered a "bug" when the markdown file is not in the vscode workspace directory.

I have the following files in my project folder:

```
project/
  docs/
    manuscript.md
    manuscript.bib
```

and the `manuscript.md` YAML metafile block containing:

```
bibliography: manuscript.bib
```

But, when I save `manuscript.md` after a change, the extension leaves a log:

```
Looking for file: c:\Users\...\project\manuscript.bib
```

and obviously not functioning properly.

My desired behavior of the extension is to `cwd` to the document's directory before running its functionality.

Thanks

**Comment by notZaki** [comment]
Thanks for noticing this. There is indeed something wrong with the how the paths are resolved.

In the meanwhile, try wrapping the bib file in square brackets, like so:
```
bibliography: [manuscript.bib]
```
That'll make the extension use an older function which should attempt to use the relative path (it'll look for two bib files, one relative to `cwd` and one relative to project root).
