### ISSUE TITLE
Can't produce citation information when exporting using pandoc

### ISSUE THREAD

**Issue by clay4shin** [notZaki/PandocCiter#6]
Thank you so much for making this awesome extension!
I was able to install this and use it in the markdown document but when I tried to export the document to another format such as pdf or docx using another extension "vscode-pandoc", the code (e.g., [@Author2008]) appears as it is, not the actual citation information. Am I missing something about this extension, or is it something that should be resolved with vscode-pandoc?

**Comment by notZaki** [comment]
The citations should appear formatted in the output if the [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) filter is used. 

As an example, the command for exporting to docx is along the lines of
```
pandoc inputfile.md -o outputfile.docx
```
and to get citations to format, it would instead be changed to
```
pandoc --filter pandoc-citeproc inputfile.md -o outputfile.docx
```
The above is assuming that the markdown file contains a YAML header with a valid `bibliography` field.
Alternatively, if a default bib file is being used for all markdown documents (i.e. YAML header does not contain bibliography field), then the pandoc command would be:
```
pandoc --bibliography path/to/default.bib --filter pandoc-citeproc inputfile.md -o outputfile.docx
```

I don't use the vscode-pandoc extension, but I think adding `--filter pandoc-citeproc` to the extensions's appropriate `optString` config should do the trick.

**Comment by clay4shin** [comment]
Thank you very much! I will try that method :)

**Comment by clay4shin** [comment]
This worked! Thank you so much! 👍
