### ISSUE TITLE
Issues with path in Windows

### ISSUE THREAD

**Issue by DOFfactory** [notZaki/PandocCiter#8]
Hi, I have issues with your plugin when giving absolute path to a Dropbox file. I know I have saved the entries to the `.bib` file, however, pandoc-citer still states that no references are there. I tried all the possible paths. I assume the problem is related with the difference between linux `../..` and Windows `..\..` paths. Could you please clarify what should be the correct use?

**Comment by notZaki** [comment]
I don't think the slash should have an effect.

For example, the monstrosity below still ends up working for me on Windows.
```
bibliography: [C:/Users\username/Dropbox\test dir/refs.bib]
```

Could you enable the log by setting `PandocCiter.ShowLog: true` in vscode's settings and checking what gets printed in the log?
The log can be viewed by `Ctrl Shift U` followed by picking `PandocCiter` from dropdown list.

If it stops after `Looking for .bib file: <path to bib>`, then I would double check the path---maybe by copy/pasting it into the file browser.

**Comment by DOFfactory** [comment]
OK, thanks for the follow-up, I made it working again. I think the issue was with the copy & paste of the path, indeed. 

Other thing is, whenever I start to type the @, the pop-up window opens, however, all the references are there double ot triple the times. Do we know the reason? I do not have those duplicates in my bib file.

![image](https://user-images.githubusercontent.com/10846169/68996285-2bbbca80-0898-11ea-94e6-88dc8771d254.png)

**Comment by notZaki** [comment]
Sometimes the bib file is loaded multiple times resulting in duplicated---often happens if the path was updated. 

Try reloading vscode (`Ctrl R`) or closing/opening it and hopefully the duplicates will be gone.

**Comment by DOFfactory** [comment]
I see, can this be somehow avoided? Maybe loading always 1x the file and reload it again whenever it is being re-written?

**Comment by notZaki** [comment]
I should clarify: I meant that duplicates are created if the path was updated/edited from within the markdown file. 

For example, suppose the markdown file contains `bibliography: refs.bib`. If that bib file is copy/pasted to a new folder and the markdown file is updated to `bibliography: newfolder/refs.bib` then this will create duplicates. 
This could be avoided by making the extension forget about `refs.bib` before loading `newfolder/refs.bib`. I might look into this later.

My guess was that something similar happened and created the duplicates you saw.
Did the duplicates disappear after reloading/refreshing vscode?

**Comment by DOFfactory** [comment]
Hi, your analysis is correct, reloading got rid of the duplicates. However, this is not an efficient way of dealing with this issue in my opinion for 2 reasons:

- my workflow (academic writing) includes that I look up literature and I add these into my reference manager (JabRef) while I am typing. This means, every time I add something and save the `.bib` file, the problem will re-occur
- I have open multiple files, and restarting VSCode is not the best/most efficient way of dealing with this issue

If we could get rid of the duplicates (that appear only in VSCode) that would be great!

**Comment by notZaki** [comment]
- Updating the `.bib` file itself should not create duplicates in vscode. The console log should show `Bib file watcher - responding to change in <bib file>`.
- Multiple files with different bibliography fields will indeed be a problem because if `file1.md` uses `refs1.bib`, while `file2.md` uses `refs2.bib`, then vscode will show suggestion from both bib files, including duplicates if the two bib files have any identical keys. I'll look for a way to remove duplicates for this situation.

**Comment by DOFfactory** [comment]
The first point does not explain the triple amount of entries, as I moved the file only 1x (and renamed it). I think you are right with 2), as I do have various bib libraries for different files opened in tabs.

**Comment by notZaki** [comment]
Hmm, then I'm not sure about the triple entries.

The only other scenario is if the capitalization is changed, e.g. if `bibliography: refs.bib` is changed to `bibligraophy: refs.biB` then that also creates duplicates, but that's because paths are not case-sensitive in windows.

**Comment by notZaki** [comment]
The latest release (0.4.0) should now forget suggestions from any unused bib paths, which should hopefully prevent duplicates from ever showing up.

It also means that when working on multiple markdown files with different bib paths, the citation suggestions won't leak across files.

**Comment by DOFfactory** [comment]
Thanks, much appreciated the quick implementation. I will test it and let you know how it works.

**Comment by notZaki** [comment]
For completeness, and in case anyone reads this later:

- Version 0.4.1 has a new configuration `PandocCiter.ForgetUnusedBib` which can be set to `false` to disable the new forgetting feature.
- In my first reply, I mentioned that the extension will accept paths with mixes slashes, e.g.
```
bibliography: [C:/Users\username/Dropbox\test dir/refs.bib]
```
but please don't do this in practice, because this is not valid YAML. Pandoc (or knitr, etc) will likely throw an error when rendering the document unless the slashes are changed to `/` or `\\`.
